# Generated by Django 2.2.12 on 2021-02-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth', '0003_graphtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemratureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.FloatField(default=0.0, null=True)),
                ('set_temprature', models.FloatField(default=0.0, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
