# Generated by Django 2.2.12 on 2021-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth', '0004_temraturedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
