# Generated by Django 2.2.12 on 2021-03-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_auth', '0005_sensors'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
